import React, { useState } from 'react';
import { Sprout, TrendingUp, Calendar, Droplet, ArrowRight, RefreshCw, BarChart2, ShieldCheck, HelpCircle } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';
import { useToast } from '../context/ToastContext';

export const CropRecommender: React.FC = () => {
  const { t } = useLanguage();
  const { showToast } = useToast();
  
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any | null>(null);

  // Form Fields
  const [soilType, setSoilType] = useState('Clayey');
  const [ph, setPh] = useState(6.5);
  const [n, setN] = useState(60);
  const [p, setP] = useState(45);
  const [k, setK] = useState(50);
  const [rainfall, setRainfall] = useState(800);
  const [temperature, setTemperature] = useState(26);
  const [humidity, setHumidity] = useState(60);
  const [area, setArea] = useState(2);
  const [season, setSeason] = useState('Kharif');
  const [budget, setBudget] = useState(25000);
  const [irrigation, setIrrigation] = useState('Canal');
  const [location, setLocation] = useState('Northern Region');

  const handleRecommend = (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    // Simulate AI model calculation
    setTimeout(() => {
      setLoading(false);
      
      // Determine crop mock logic based on inputs
      let crop = "Wheat";
      let confidence = 94;
      let yieldEst = "4.2 Tons/Acre";
      let profitEst = "₹58,000 / Acre";
      let waterReq = "Medium (350-400mm)";
      let fert = "Apply Nitrogen NPK 12:32:16 (50kg/acre) during planting, followed by Urea top-dressing at 30 days.";
      let harvest = "110-120 days from planting";

      if (soilType === 'Loamy' && ph > 6.0) {
        crop = "Basmati Rice";
        confidence = 92;
        yieldEst = "3.8 Tons/Acre";
        profitEst = "₹72,000 / Acre";
        waterReq = "High (1200-1400mm)";
        fert = "Apply Zinc Sulphate (10kg/acre) alongside compost (5 tons/acre) for high aromatic yield.";
        harvest = "130-145 days";
      } else if (soilType === 'Sandy') {
        crop = "Groundnuts";
        confidence = 88;
        yieldEst = "2.1 Tons/Acre";
        profitEst = "₹46,000 / Acre";
        waterReq = "Low (200-250mm)";
        fert = "Apply Gypsum (200kg/acre) during flowering stage to aid pegging.";
        harvest = "105-115 days";
      } else if (ph < 5.5) {
        crop = "Tea / Potato";
        confidence = 89;
        yieldEst = "8.5 Tons/Acre (Potato)";
        profitEst = "₹52,000 / Acre";
        waterReq = "Medium (500mm)";
        fert = "Apply Ammonium Sulphate as a Nitrogen source to maintain slight acidity.";
        harvest = "90-100 days (Potato)";
      }

      setResult({
        crop,
        confidence,
        yieldEst,
        profitEst,
        waterReq,
        fert,
        harvest,
        schedule: [
          { step: "Land Preparation", time: "Week 1", desc: "Tuttle plow field and add compost" },
          { step: "Sowing", time: "Week 2", desc: "Sow seeds at 3-5cm depth with NPK base" },
          { step: "First Irrigation", time: "Week 5", desc: "Critical crown root initiation stage" },
          { step: "Weeding", time: "Week 8", desc: "Manual weeding or targeted eco-herbicide spray" },
          { step: "Harvesting", time: "Week 16", desc: "Mow and thresh crops during dry outlook" },
        ]
      });
      showToast("Recommendation generated by AgriAI model!", "success");
    }, 1500);
  };

  return (
    <div className="flex flex-col gap-6 w-full max-w-6xl mx-auto">
      
      {/* Title */}
      <div>
        <h1 className="text-xl sm:text-2xl font-bold text-gray-800 dark:text-gray-100 flex items-center gap-1.5">
          <Sprout className="w-6 h-6 text-emerald-600" />
          {t('cropRecommend')}
        </h1>
        <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">
          Provide your soil measurements and regional conditions to find the optimal high-yielding crops.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Input Form Column */}
        <form 
          onSubmit={handleRecommend}
          className="lg:col-span-5 p-6 rounded-3xl border border-gray-100 dark:border-slate-800/80 bg-white dark:bg-slate-950 flex flex-col gap-4 shadow-sm"
        >
          <div className="grid grid-cols-2 gap-4">
            
            {/* Soil Type */}
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-bold text-gray-400 uppercase">{t('soilType')}</label>
              <select
                value={soilType}
                onChange={(e) => setSoilType(e.target.value)}
                className="w-full p-2.5 rounded-xl border border-gray-200 dark:border-slate-800 bg-transparent dark:bg-slate-900/30 text-xs focus:ring-2 focus:ring-emerald-500/20"
              >
                <option value="Clayey">Clayey</option>
                <option value="Loamy">Loamy</option>
                <option value="Sandy">Sandy</option>
                <option value="Black Cotton">Black Cotton</option>
                <option value="Red Soil">Red Soil</option>
              </select>
            </div>

            {/* pH */}
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-bold text-gray-400 uppercase">Soil pH ({ph.toFixed(1)})</label>
              <input
                type="range"
                min="3"
                max="10"
                step="0.1"
                value={ph}
                onChange={(e) => setPh(parseFloat(e.target.value))}
                className="w-full accent-emerald-600 mt-2"
              />
            </div>

            {/* Nitrogen */}
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-bold text-gray-400 uppercase">Nitrogen (N: {n} ppm)</label>
              <input
                type="range"
                min="0"
                max="140"
                value={n}
                onChange={(e) => setN(parseInt(e.target.value))}
                className="w-full accent-emerald-600 mt-2"
              />
            </div>

            {/* Phosphorus */}
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-bold text-gray-400 uppercase">Phosphorus (P: {p} ppm)</label>
              <input
                type="range"
                min="0"
                max="140"
                value={p}
                onChange={(e) => setP(parseInt(e.target.value))}
                className="w-full accent-emerald-600 mt-2"
              />
            </div>

            {/* Potassium */}
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-bold text-gray-400 uppercase">Potassium (K: {k} ppm)</label>
              <input
                type="range"
                min="0"
                max="140"
                value={k}
                onChange={(e) => setK(parseInt(e.target.value))}
                className="w-full accent-emerald-600 mt-2"
              />
            </div>

            {/* Rainfall */}
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-bold text-gray-400 uppercase">Expected Rain ({rainfall}mm)</label>
              <input
                type="range"
                min="100"
                max="2000"
                step="50"
                value={rainfall}
                onChange={(e) => setRainfall(parseInt(e.target.value))}
                className="w-full accent-emerald-600 mt-2"
              />
            </div>
          </div>

          <div className="border-t border-gray-50 dark:border-slate-800/40 my-1 pt-3 grid grid-cols-2 gap-4">
            
            {/* Region / Location */}
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-bold text-gray-400 uppercase">{t('location')}</label>
              <select
                value={location}
                onChange={(e) => setLocation(e.target.value)}
                className="w-full p-2.5 rounded-xl border border-gray-200 dark:border-slate-800 bg-transparent dark:bg-slate-900/30 text-xs focus:ring-2 focus:ring-emerald-500/20"
              >
                <option value="Northern Region">Northern Region</option>
                <option value="Southern Peninsula">Southern Peninsula</option>
                <option value="Eastern Delta">Eastern Delta</option>
                <option value="Dry Western Zone">Dry Western Zone</option>
              </select>
            </div>

            {/* Irrigation */}
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-bold text-gray-400 uppercase">{t('irrigation')}</label>
              <select
                value={irrigation}
                onChange={(e) => setIrrigation(e.target.value)}
                className="w-full p-2.5 rounded-xl border border-gray-200 dark:border-slate-800 bg-transparent dark:bg-slate-900/30 text-xs focus:ring-2 focus:ring-emerald-500/20"
              >
                <option value="Canal">Canal System</option>
                <option value="Tubewell">Borewell/Tubewell</option>
                <option value="Rainfed">Rainfed Only</option>
                <option value="Drip">Drip Irrigation</option>
              </select>
            </div>

            {/* Land Area */}
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-bold text-gray-400 uppercase">Land Area (Acres)</label>
              <input
                type="number"
                min="0.5"
                step="0.5"
                value={area}
                onChange={(e) => setArea(parseFloat(e.target.value))}
                className="w-full p-2.5 rounded-xl border border-gray-200 dark:border-slate-800 bg-transparent dark:bg-slate-900/30 text-xs focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500"
              />
            </div>

            {/* Season */}
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-bold text-gray-400 uppercase">{t('season')}</label>
              <select
                value={season}
                onChange={(e) => setSeason(e.target.value)}
                className="w-full p-2.5 rounded-xl border border-gray-200 dark:border-slate-800 bg-transparent dark:bg-slate-900/30 text-xs focus:ring-2 focus:ring-emerald-500/20"
              >
                <option value="Kharif">Kharif (Monsoon)</option>
                <option value="Rabi">Rabi (Winter)</option>
                <option value="Zaid">Zaid (Summer)</option>
              </select>
            </div>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full bg-gradient-to-r from-emerald-600 to-teal-500 hover:scale-[1.01] text-white font-bold py-3.5 rounded-2xl shadow-md transition-all flex items-center justify-center gap-2 mt-4"
          >
            {loading ? (
              <>
                <RefreshCw className="w-5 h-5 animate-spin" />
                Analyzing Soil Metrics...
              </>
            ) : (
              <>
                <Sprout className="w-5 h-5" />
                {t('btnRecommend')}
              </>
            )}
          </button>
        </form>

        {/* Output Recommendation Result Column */}
        <div className="lg:col-span-7">
          {result ? (
            <div className="flex flex-col gap-6">
              
              {/* Highlight best crop */}
              <div className="p-6 rounded-3xl border border-emerald-100 dark:border-emerald-950/30 bg-emerald-500/[0.04] flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 relative overflow-hidden">
                <div className="absolute top-0 right-0 opacity-10 translate-x-12 -translate-y-8 pointer-events-none">
                  <Sprout className="w-56 h-56" />
                </div>
                
                <div className="relative z-10 flex flex-col gap-1">
                  <span className="text-[10px] font-extrabold text-emerald-600 dark:text-emerald-400 uppercase tracking-widest">{t('resultBestCrop')}</span>
                  <h2 className="text-3xl font-extrabold text-gray-800 dark:text-gray-100 tracking-tight">
                    {result.crop}
                  </h2>
                  <div className="flex items-center gap-1.5 mt-2 bg-emerald-100 dark:bg-emerald-950/80 px-3 py-1 rounded-full text-emerald-800 dark:text-emerald-300 w-fit text-xs font-bold">
                    <ShieldCheck className="w-3.5 h-3.5" />
                    {result.confidence}% Confidence
                  </div>
                </div>

                <div className="relative z-10 grid grid-cols-2 gap-4 bg-white dark:bg-slate-900 border border-gray-100 dark:border-slate-800/80 p-4 rounded-2xl shadow-sm min-w-[14rem]">
                  <div>
                    <span className="text-[10px] text-gray-400 uppercase font-bold">{t('resultYield')}</span>
                    <p className="text-sm font-bold text-gray-800 dark:text-gray-200 mt-0.5">{result.yieldEst}</p>
                  </div>
                  <div>
                    <span className="text-[10px] text-gray-400 uppercase font-bold">{t('resultProfit')}</span>
                    <p className="text-sm font-bold text-emerald-600 dark:text-emerald-400 mt-0.5">{result.profitEst}</p>
                  </div>
                </div>
              </div>

              {/* Water & Fertilizer cards */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="p-5 rounded-2xl border border-gray-100 dark:border-slate-800 bg-white dark:bg-slate-950 flex flex-col gap-2">
                  <div className="flex items-center gap-2 text-xs font-bold text-cyan-600 dark:text-cyan-400 uppercase">
                    <Droplet className="w-4.5 h-4.5" />
                    Water Requirement
                  </div>
                  <p className="text-xs font-semibold text-gray-700 dark:text-gray-300 leading-relaxed">
                    {result.waterReq}
                  </p>
                </div>
                <div className="p-5 rounded-2xl border border-gray-100 dark:border-slate-800 bg-white dark:bg-slate-950 flex flex-col gap-2">
                  <div className="flex items-center gap-2 text-xs font-bold text-amber-500 uppercase">
                    <BarChart2 className="w-4.5 h-4.5" />
                    Fertilizer Recommendation
                  </div>
                  <p className="text-xs font-semibold text-gray-700 dark:text-gray-300 leading-relaxed">
                    {result.fert}
                  </p>
                </div>
              </div>

              {/* Timeline schedule */}
              <div className="p-6 rounded-3xl border border-gray-100 dark:border-slate-800 bg-white dark:bg-slate-950 shadow-sm flex flex-col gap-4">
                <h3 className="text-sm font-bold text-gray-800 dark:text-gray-200 flex items-center gap-2">
                  <Calendar className="w-4.5 h-4.5 text-emerald-600" />
                  Cultivation & Schedule Details
                </h3>
                
                <div className="relative border-l-2 border-emerald-500/20 ml-3 pl-6 space-y-5">
                  {result.schedule.map((s: any, idx: number) => (
                    <div key={idx} className="relative group">
                      {/* Node point */}
                      <span className="absolute -left-[31px] top-1 w-3 h-3 rounded-full bg-emerald-500 border-2 border-white dark:border-slate-950 shadow group-hover:scale-115 transition-transform" />
                      <div className="flex justify-between items-center text-xs font-bold text-gray-400">
                        <span>{s.step}</span>
                        <span className="text-emerald-600 dark:text-emerald-400 font-semibold">{s.time}</span>
                      </div>
                      <p className="text-xs text-gray-600 dark:text-gray-300 mt-0.5">
                        {s.desc}
                      </p>
                    </div>
                  ))}
                </div>
              </div>

            </div>
          ) : (
            <div className="h-full min-h-[22rem] rounded-3xl border border-dashed border-gray-200 dark:border-slate-850 flex flex-col justify-center items-center p-8 text-center text-gray-400 dark:text-gray-600">
              <Sprout className="w-16 h-16 opacity-30 animate-float" />
              <h3 className="font-bold text-gray-600 dark:text-gray-400 mt-4">No Recommendation Yet</h3>
              <p className="text-xs max-w-sm mt-1">
                Fill in the soil attributes, nutrient parameters, and region on the left, then click submit to run the model.
              </p>
            </div>
          )}
        </div>

      </div>

    </div>
  );
};
export default CropRecommender;
